version: '3.8'

services:
  patrones-service:
    build:
      context: .
    container_name: patrones-service
    mem_limit: 512m
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/patrones-service?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
    depends_on:
      - mysql-db
    networks:
      - patrones-networks

  mysql-db:
    image: mysql:8.0
    container_name: patrones-mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: patrones-service
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    networks:
      - patrones-networks
    volumes:
      - mysql-data:/var/lib/mysql

networks:
  patrones-networks:
    driver: bridge

volumes:
  mysql-data:
    driver: local
